### ISSUE TITLE
First input not loading and wrong macro viewing

### ISSUE THREAD

**Issue by Button-Pushing** [ZiLko/platformer_ghosts#10]
https://github.com/user-attachments/assets/b3105435-3229-421c-a562-66c6736629cb
It showed the wrong replay logo and the first input didn't go through

**Comment by Button-Pushing** [comment]
Wrong replay time, not logo, sry

**Comment by Zilko** [comment]
replay time is showing the lowest time

for the first input thing read my response to ur previous issue

**Comment by Button-Pushing** [comment]
Which one?

**Comment by Zilko** [comment]
![image](https://github.com/user-attachments/assets/4dc05743-f5f8-4788-9ca9-dbe05204b330)

**Comment by Zilko** [comment]
ill add legacy setting for watching ghosts but u should use the new one cus it fixes some other bugs

**Comment by Zilko** [comment]
and the input bug only happens on old ghosts where u holded while respawning

**Comment by Button-Pushing** [comment]
Where's the legacy option? I can't find it

**Comment by Zilko** [comment]
forgo

**Comment by Zilko** [comment]
i forcefully applied legacy mode on old ghosts and new ones will be new
