### ISSUE TITLE
Hay un problema con los niveles clasicos...

### ISSUE THREAD

**Issue by CochisAldea1505** [ZiLko/platformer_ghosts#11]
Cada vez que termino un nivel original y tengo activado el mod, se rompe el juego y me saca de el, puedes arreglarlo?

Soy de PC (Steam)
![image](https://github.com/user-attachments/assets/40a7d473-c8ab-4842-a34c-326798c82fd3)

**Comment by Zilko** [comment]
arreglado en la 1.2.1

**Comment by CochisAldea1505** [comment]
gracias
