### ISSUE TITLE
Ghosts not resetting on death in view replay

### ISSUE THREAD

**Issue by Button-Pushing** [ZiLko/platformer_ghosts#6]
While viewing ghost replays, when you die, it doesn't reset

**Comment by Button-Pushing** [comment]
It might be because I usually manually reset after dying bc it's faster

**Comment by Zilko** [comment]
i tink i fixed

**Comment by Button-Pushing** [comment]
It still stays dead

**Comment by Zilko** [comment]
sory i thought you were talking about a different bug i fixed in 1.1.3 now

**Comment by Button-Pushing** [comment]
Fixed, but it sometimes thinks you die, maybe turn on noclip for ghost?

**Comment by Zilko** [comment]
no u have to die otherwise important triggers on the level might not be triggered

**Comment by Zilko** [comment]
ofc it depends on the level but i cant just guess

**Comment by Button-Pushing** [comment]
That makes sense

**Comment by Button-Pushing** [comment]
Is there a way to "restart" or something once the player dies?
