### ISSUE TITLE
Ghosts dying when player doesnt

### ISSUE THREAD

**Issue by Button-Pushing** [ZiLko/platformer_ghosts#8]
I think I explained this badly in the other issue, (sorry about that) but the ghost dies sometimes when the player doesn't.

**Comment by Zilko** [comment]
while watching u mean?

**Comment by Button-Pushing** [comment]
Yeah

**Comment by Zilko** [comment]
how to replicate consistently do u just crash into a spike sideways

**Comment by Button-Pushing** [comment]
I could probably send ghost replay

**Comment by Button-Pushing** [comment]
Misspelled ghost, level name is dashtek
[ashtekghost.json](https://github.com/user-attachments/files/17995706/ashtekghost.json)

**Comment by Zilko** [comment]
its more of a ghost recording issue instead of a ghost playing issue so no point

**Comment by Zilko** [comment]
i changed the watching system this shouldnt happen anymore but i will say theres also a  bug that got added in ghosts where u held while respawning from the start but this is unavoidable
