### ISSUE TITLE
Show inputs on mobile

### ISSUE THREAD

**Issue by Button-Pushing** [ZiLko/platformer_ghosts#9]
If it's not too hard, it'd be cool to have the inputs show as you're viewing a ghost

**Comment by Zilko** [comment]
ignore 1.2.4 changelog it did not work will actually add when i have time again

**Comment by Zilko** [comment]
nvm it did work i think i just didnt have node ids but i fixed that its added

**Comment by Button-Pushing** [comment]
Works great, but left press shows as both pressed

**Comment by Button-Pushing** [comment]
Also controls don't go away on other levels, even classic ones(maybe because i exited before the run ended idk)
